# If you need to use OpenAI models
OPENAI_API_KEY = "your_openai_api_key"

# If you need to use Azure OpenAI services
# AZURE_OPENAI_API_KEY = "<YOUR_API_KEY>"
# AZURE_OPENAI_ENDPOINT = "<YOUR_AZURE_OPENAI_ENDPOINT"
# API_VERSION = "2024-05-01-preview"

# tool credentials
WOLFRAM_ALPHA_APPID= "<YOUR_WOLFRAMALPHA_APP_ID>"
